### ISSUE TITLE
.deb package not working on systems that use dh-nss (like debian/trixie)

### ISSUE THREAD

**Issue by frebib** [petski/nss-docker-ng#12]
Missing changelog seems to prevent build:
```
$ dpkg-buildpackage -uc -us
dpkg-buildpackage: error: cannot open file debian/changelog: No such file or directory
```

What am I missing?
Thanks in advance

**Comment by petski** [comment]
The README contains instructions to download and install a pre-build Debian/Ubuntu package, so you don't have to build it yourself.

In case you want to build it yourself, see https://github.com/petski/nss-docker-ng/blob/694c237ee509a837209d49973d9621a6a38d9966/.github/workflows/tag.yml#L88 for the steps I use to automatically build and release the Debian/Ubuntu package (for your question especially the dch part).

**Comment by frebib** [comment]
Thanks, I'll take a look.
I did try the Ubuntu Noble package (I'm running Debian Testing/Trixie) but it seems not to be working; it's possibly some screw-up on my part.

**Comment by petski** [comment]
I managed to reproduce this issue. Steps to reproduce:

```
docker run --rm -i -t --privileged debian:trixie
apt-get update && apt-get install -y wget dh-nss docker.io
wget 'https://launchpad.net/~petski/+archive/ubuntu/nss-docker-ng/+build/28464588/+files/nss-docker-ng_1.0.6-1~ubuntu.24.04~noble_amd64.deb'
dpkg -i nss-docker-ng_1.0.6-1~ubuntu.24.04~noble_amd64.deb
service docker start
docker run --name my-app -d hashicorp/http-echo -listen=:80 -text="✅ it works!"
getent hosts my-app.docker
```

Somehow `dh-nss` doesn't kick in to change `/etc/nsswitch.conf`. I will fix this later.

As a work around, you can fix this by adding `docker_ng` on the `hosts`-line in `/etc/nsswitch.conf`, preferably between `files` and `dns`. I.e. `hosts: files docker_ng dns`

**Comment by frebib** [comment]
In my testing, installing the package did add `docker_ng` to nsswitch, but container resolution did not work (it also seemed to break all other resolution on the system, such as to deb.debian.org, until I removed it again). I didn't try too hard to make it work after that though.
