### ISSUE TITLE
Implement subdomain wildcard for containers

### ISSUE THREAD

**Issue by pyhedgehog** [petski/nss-docker-ng#9]
If your container supports answering on several domain names (like tenants in [Saltcorn](https://github.com/saltcorn/saltcorn/)), you'll need to be able to access to it using `*.container-name.docker` in addition to `container-name.docker`.

**Comment by petski** [comment]
@pyhedgehog thanks for your contribution.

Approach I'm thinking of is enabling this feature via an optional `.com.github.petski.nss-docker-ng.container-subdomains-allowed` label, which defaults to false.

**Comment by petski** [comment]
@pyhedgehog can you please test the feature via PR #10 and let me know the outcome?

**Comment by pyhedgehog** [comment]
@petski It's alive! :-) I mean... thanks, I tested this patch and it works as it should.

**Comment by petski** [comment]
Just released this in v1.0.4. Enjoy!
